version: '3'
services:
  web:
    build: .
    volumes:
    - .:/code
    ports:
    - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/bazaar_database_development
  db:
    image: postgres